# INSTALL and SOURCE_GROUP commands for OSG/OT/Producer Modules

# Required Vars:
# ${LIB_NAME}
# ${TARGET_H}

# Optional Vars:
# ${HEADER_INSTALL_DIR}

IF(HEADER_INSTALL_DIR)
    SET(INSTALL_INCDIR include/${HEADER_INSTALL_DIR})
ELSE()
    SET(INSTALL_INCDIR include/${LIB_NAME})
ENDIF()

SET(INSTALL_BINDIR bin)
IF(WIN32)
    SET(INSTALL_LIBDIR bin)
    SET(INSTALL_ARCHIVEDIR lib)
ELSE()
    SET(INSTALL_LIBDIR lib${LIB_POSTFIX})
    SET(INSTALL_ARCHIVEDIR lib${LIB_POSTFIX})
ENDIF()

SET(HEADERS_GROUP "Header Files")

SOURCE_GROUP(
    ${HEADERS_GROUP}
    FILES ${TARGET_H}
)

IF(MSVC AND OSG_MSVC_VERSIONED_DLL)
    HANDLE_MSVC_DLL()
ENDIF()

INSTALL(
    TARGETS ${LIB_NAME}
    RUNTIME DESTINATION ${INSTALL_BINDIR} COMPONENT libopenscenegraph
    LIBRARY DESTINATION ${INSTALL_LIBDIR} COMPONENT libopenscenegraph
    ARCHIVE DESTINATION ${INSTALL_ARCHIVEDIR} COMPONENT libopenscenegraph-dev    
)

IF(MSVC AND NOT CMAKE_BUILD_TYPE STREQUAL "Release")
    # Get the actual output name of the DLL to find the matching PDB
    GET_TARGET_PROPERTY(OUTPUT_NAME ${LIB_NAME} OUTPUT_NAME)
    IF(NOT OUTPUT_NAME)
        SET(OUTPUT_NAME ${LIB_NAME})
    ENDIF()

    # Get the PREFIX property (for versioned DLLs)
    # Note: GET_TARGET_PROPERTY returns "PREFIX-NOTFOUND" if the property doesn't exist
    SET(PREFIX "")
    GET_TARGET_PROPERTY(PREFIX_VALUE ${LIB_NAME} PREFIX)
    IF(NOT PREFIX_VALUE STREQUAL "PREFIX-NOTFOUND")
        SET(PREFIX ${PREFIX_VALUE})
    ENDIF()

    # Try the output name directly (handles both versioned and non-versioned cases)
    INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/${OUTPUT_NAME}${CMAKE_BUILD_POSTFIX}.pdb DESTINATION ${INSTALL_BINDIR} COMPONENT libopenscenegraph OPTIONAL)

    # Try with PREFIX (for versioned DLLs like osg147-osgQOpenGLd.pdb)
    IF(PREFIX)
        INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/${PREFIX}${OUTPUT_NAME}${CMAKE_BUILD_POSTFIX}.pdb DESTINATION ${INSTALL_BINDIR} COMPONENT libopenscenegraph OPTIONAL)
    ENDIF()

    # Fallback: try the most common naming pattern
    INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/osg${OPENSCENEGRAPH_SOVERSION}-${OUTPUT_NAME}${CMAKE_BUILD_POSTFIX}.pdb DESTINATION ${INSTALL_BINDIR} COMPONENT libopenscenegraph OPTIONAL)
ENDIF()

IF(NOT OSG_COMPILE_FRAMEWORKS)
    INSTALL (
        FILES        ${TARGET_H}
        DESTINATION ${INSTALL_INCDIR}
        COMPONENT libopenscenegraph-dev
    )
ELSE()
    SET(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
    SET(CMAKE_INSTALL_RPATH "${OSG_COMPILE_FRAMEWORKS_INSTALL_NAME_DIR}")
    
    SET_TARGET_PROPERTIES(${LIB_NAME} PROPERTIES
         FRAMEWORK TRUE
         FRAMEWORK_VERSION ${OPENSCENEGRAPH_SOVERSION}
         PUBLIC_HEADER  "${TARGET_H}"
         INSTALL_NAME_DIR "${OSG_COMPILE_FRAMEWORKS_INSTALL_NAME_DIR}"
    )
    # MESSAGE("${OSG_COMPILE_FRAMEWORKS_INSTALL_NAME_DIR}")
ENDIF()

